#include "game_dispatch_emitter.h"

#include <algorithm>
#include <map>
#include <sstream>
#include <utility>
#include <vector>

#include "fmt/format.h"

namespace PSXRecomp {

bool emit_game_dispatch(const CodeGenerator& codegen,
                        const PS1Executable& exe,
                        const std::set<uint32_t>& dispatch_addrs,
                        const std::string& ranges_manifest,
                        std::string& out,
                        std::string& error) {
    return emit_game_dispatch(std::vector<GameDispatchUnit>{{&codegen, dispatch_addrs}},
                              exe, ranges_manifest, out, error);
}

bool emit_game_dispatch(const std::vector<GameDispatchUnit>& units,
                        const PS1Executable& exe,
                        const std::string& ranges_manifest,
                        std::string& out,
                        std::string& error) {
    if (units.empty() || !units.front().codegen) {
        error = "emit_game_dispatch: no compile to dispatch";
        return false;
    }
    const bool cps = units.front().codegen->cps_enabled();
    std::ostringstream ds;
    ds << "/* Generated by PSXRecomp - dynamic dispatch table */\n";
    ds << "#include \"psx_runtime.h\"\n\n";
    ds << "extern void psx_check_interrupts_dispatch_entry(CPUState* cpu, uint32_t resume_pc);\n\n";
    ds << "extern int dirty_ram_text_native_ok_ranges_from(const uint32_t* lo_len_pairs, uint32_t count, uint32_t exec_pc);\n\n";
    ds << "extern int dirty_ram_text_native_ok_ranges(const uint32_t* lo_len_pairs, uint32_t count);\n\n";

    // Forward declarations
    ds << "/* Forward declarations for all recompiled functions */\n";
    for (const auto& unit : units) {
        for (uint32_t addr : unit.dispatch_addrs) {
            ds << fmt::format("extern void func_{:08X}(CPUState* cpu);\n", addr);
        }
    }
    ds << "\n";

    // Text membership is byte identity: physical, the same RAM in every
    // segment. A PC in another segment is still game text, which is what
    // routes a segment miss to the interpreter instead of the BIOS shell.
    uint32_t game_text_start = exe.load_address() & 0x1FFFFFFFu;
    uint32_t game_text_end = game_text_start + exe.code_size();
    ds << "int psx_game_address_in_text(uint32_t addr) {\n";
    ds << "    uint32_t phys = addr & 0x1FFFFFFFu;\n";
    ds << fmt::format("    return phys >= 0x{:08X}u && phys < 0x{:08X}u;\n",
                      game_text_start, game_text_end);
    ds << "}\n\n";

    // Materialize one sorted data table for dispatch and entry probes. A
    // giant sparse switch is catastrophically slow in Debug/-O0 builds:
    // GCC lowers X4's roughly 60K cases to a multi-megabyte linear compare
    // chain. Binary search stays O(log N) at every optimizer level and
    // avoids emitting the same case set twice.
    // `key` and `resume` are the PCs the guest executes, routed through the
    // unit's runtime_pc() (docs/SEGMENT_AWARE_CODE.md §5.2); `addr` and
    // `owner` are compile identities (func_ names, .ranges owners). resume 0
    // means "entry at the prologue", not a PC.
    struct DispatchRecord {
        uint32_t addr;
        uint32_t key;
        uint32_t resume;
        uint32_t owner;
        uint32_t range_index;
        uint32_t range_count;
    };
    std::vector<DispatchRecord> records;
    for (const auto& unit : units) {
        const CodeGenerator& codegen = *unit.codegen;
        for (uint32_t addr : unit.dispatch_addrs)
            records.push_back({addr, codegen.runtime_pc(addr), 0, addr, 0, 0});
        if (cps) {
            const auto& conts = codegen.cps_continuations();
            for (const auto& [cont, owner] : conts) {
                if (unit.dispatch_addrs.count(cont)) continue;
                // A continuation owned by a fail-closed stub is no more
                // executable than the stub entry itself.
                if (!unit.dispatch_addrs.count(owner)) continue;
                records.push_back({cont, codegen.runtime_pc(cont), codegen.runtime_pc(cont),
                                   owner, 0, 0});
            }
        }
    }
    // Sort by PHYSICAL word, then by the full PC: the lookup indexes (or
    // binary-searches) the physical word and then requires the exact PC. A
    // word has one row per segment compiled for it, adjacent: the home
    // compile's and those of its segment variants (§5.4). Within one compile
    // the code segment is fixed, so two rows on one word are the same PC.
    std::sort(records.begin(), records.end(),
              [](const DispatchRecord& a, const DispatchRecord& b) {
                  const uint32_t pa = a.key & 0x1FFFFFFFu, pb = b.key & 0x1FFFFFFFu;
                  return pa != pb ? pa < pb : a.key < b.key;
              });
    bool shared_words = false;
    for (size_t i = 1; i < records.size(); ++i) {
        if (records[i].key == records[i - 1].key) {
            error = fmt::format(
                "dispatch rows 0x{:08X} and 0x{:08X} are the same PC 0x{:08X}: they "
                "share a physical word in one code segment "
                "(docs/SEGMENT_AWARE_CODE.md §5.5)",
                records[i - 1].addr, records[i].addr, records[i].key);
            return false;
        }
        if ((records[i].key & 0x1FFFFFFFu) == (records[i - 1].key & 0x1FFFFFFFu))
            shared_words = true;
    }

    // Attach the exact CFG instruction ranges from the manifest to every
    // dispatch owner. Mid-function alias wrappers have no separate F record,
    // so resolve them to the containing host range. Mutable data and
    // jump-table gaps sharing a page remain deliberately excluded.
    using CodeRange = std::pair<uint32_t, uint32_t>;  // virtual lo, byte len
    std::map<uint32_t, std::vector<CodeRange>> function_ranges;
    {
        std::istringstream input(ranges_manifest);
        std::string line;
        uint32_t current_owner = 0;
        while (std::getline(input, line)) {
            std::istringstream fields(line);
            char kind = 0;
            fields >> kind;
            if (kind == 'F') {
                fields >> std::hex >> current_owner;
                function_ranges[current_owner];
            } else if (kind == 'R' && current_owner != 0) {
                uint32_t lo = 0, len = 0;
                fields >> std::hex >> lo >> len;
                if (len != 0)
                    function_ranges[current_owner].push_back({lo, len});
            }
        }
    }
    std::vector<CodeRange> flat_ranges;
    std::map<uint32_t, std::pair<uint32_t, uint32_t>> owner_spans;
    auto resolve_owner_ranges = [&](uint32_t owner)
        -> const std::vector<CodeRange>* {
        auto exact = function_ranges.find(owner);
        if (exact != function_ranges.end() && !exact->second.empty())
            return &exact->second;
        for (const auto& [entry, ranges] : function_ranges) {
            (void)entry;
            for (const auto& [lo, len] : ranges) {
                const uint64_t hi = (uint64_t)lo + len;
                if (owner >= lo && (uint64_t)owner < hi) return &ranges;
            }
        }
        return nullptr;
    };
    for (auto& rec : records) {
        auto cached = owner_spans.find(rec.owner);
        if (cached == owner_spans.end()) {
            const uint32_t first = (uint32_t)flat_ranges.size();
            const auto* ranges = resolve_owner_ranges(rec.owner);
            if (ranges)
                flat_ranges.insert(flat_ranges.end(), ranges->begin(), ranges->end());
            const uint32_t count = (uint32_t)flat_ranges.size() - first;
            cached = owner_spans.emplace(rec.owner,
                                         std::make_pair(first, count)).first;
        }
        rec.range_index = cached->second.first;
        rec.range_count = cached->second.second;
    }

    ds << "typedef struct { uint32_t lo; uint32_t len; } PsxGameCodeRange;\n";
    ds << "static const PsxGameCodeRange k_psx_game_code_ranges[] = {\n";
    if (flat_ranges.empty()) ds << "    {0u, 0u},\n";
    for (const auto& [lo, len] : flat_ranges)
        ds << fmt::format("    {{0x{:08X}u, 0x{:X}u}},\n", lo, len);
    ds << "};\n\n";

    ds << "typedef void (*PsxGameDispatchFn)(CPUState* cpu);\n";
    ds << "typedef struct {\n";
    ds << "    uint32_t addr;\n";
    ds << "    uint32_t resume_pc;\n";
    ds << "    uint32_t range_index;\n";
    ds << "    uint32_t range_count;\n";
    ds << "    PsxGameDispatchFn fn;\n";
    ds << "} PsxGameDispatchEntry;\n\n";
    ds << "static const PsxGameDispatchEntry k_psx_game_dispatch[] = {\n";
    for (const auto& rec : records) {
        ds << fmt::format("    {{0x{:08X}u, 0x{:08X}u, {}u, {}u, func_{:08X}}},\n",
                          rec.key, rec.resume, rec.range_index, rec.range_count,
                          rec.owner);
    }
    ds << "};\n";
    ds << fmt::format("#define PSX_GAME_DISPATCH_COUNT {}u\n\n", records.size());
    // WO-6: resident dispatch keys are immutable. Index them once at build
    // time instead of binary-searching on every overlay-to-EXE call and
    // every text-validity query. This caches resolution, NEVER validity:
    // callers below still check live instruction ranges on every dispatch.
    // Bound the indexed span to one PS1 RAM image; wider tables retain the
    // binary search. No mutable cache or flag.
    const uint32_t lookup_lo = records.empty() ? 0u : (records.front().key & 0x1FFFFFFFu);
    const uint32_t lookup_hi = records.empty() ? 0u : (records.back().key & 0x1FFFFFFFu);
    bool indexed_lookup = !records.empty() && lookup_hi - lookup_lo < 0x200000u;
    for (size_t i = 0; i < records.size(); ++i) {
        if (records[i].key & 3u) indexed_lookup = false;
    }
    if (indexed_lookup) {
        // Each word indexes its FIRST row; a word's other segments follow it.
        std::vector<uint32_t> index((lookup_hi - lookup_lo) / 4u + 1u, 0u);
        for (size_t i = records.size(); i-- > 0;)
            index[((records[i].key & 0x1FFFFFFFu) - lookup_lo) / 4u] = (uint32_t)i + 1u;
        ds << "/* Immutable physical-word index; zero denotes a dispatch miss. */\n";
        ds << "static const " << (records.size() <= 65535u ? "uint16_t" : "uint32_t")
           << " k_psx_game_dispatch_index[] = {\n";
        for (size_t i = 0; i < index.size(); ++i) {
            if ((i & 15u) == 0) ds << "    ";
            ds << index[i] << "u,";
            ds << (((i & 15u) == 15u || i + 1 == index.size()) ? "\n" : " ");
        }
        ds << "};\n\n";
    }
    ds << "/* A PC carries a segment (KUSEG 0x0..., KSEG0 0x8..., KSEG1 0xA...), and\n";
    ds << " * code identity is the full PC: each body bakes the links, EPCs, fetch\n";
    ds << " * tags and store PCs of the segment it was compiled for\n";
    ds << " * (docs/SEGMENT_AWARE_CODE.md §5.5). Find the physical word's row, then\n";
    ds << " * require the exact PC. A PC in another segment at the same word is a\n";
    ds << " * segment miss: no row here, but still game text (physical), so dispatch\n";
    ds << " * interprets it and records it, and never runs this body for it. */\n";
    ds << "static const PsxGameDispatchEntry* psx_game_find_entry(uint32_t addr) {\n";
    ds << "    const uint32_t want = addr & 0x1FFFFFFFu;\n";
    if (shared_words) {
        // Segment variants (§5.4): a word may have a row per compiled
        // segment, adjacent and in PC order. Find the word's first row, then
        // the exact PC among its rows.
        if (indexed_lookup) {
            ds << fmt::format("    const uint32_t offset = want - 0x{:08X}u;\n", lookup_lo);
            ds << fmt::format("    if ((want & 3u) || offset > 0x{:X}u) return 0;\n", lookup_hi - lookup_lo);
            ds << "    const uint32_t index = k_psx_game_dispatch_index[offset >> 2];\n";
            ds << "    if (!index) return 0;\n";
            ds << "    uint32_t row = index - 1u;\n";
        } else {
            ds << "    uint32_t lo = 0, hi = PSX_GAME_DISPATCH_COUNT;\n";
            ds << "    while (lo < hi) {  /* first row whose word is >= want */\n";
            ds << "        uint32_t mid = lo + (hi - lo) / 2;\n";
            ds << "        if ((k_psx_game_dispatch[mid].addr & 0x1FFFFFFFu) < want) lo = mid + 1;\n";
            ds << "        else hi = mid;\n";
            ds << "    }\n";
            ds << "    uint32_t row = lo;\n";
        }
        ds << "    for (; row < PSX_GAME_DISPATCH_COUNT &&\n";
        ds << "           (k_psx_game_dispatch[row].addr & 0x1FFFFFFFu) == want; ++row)\n";
        ds << "        if (k_psx_game_dispatch[row].addr == addr) return &k_psx_game_dispatch[row];\n";
        ds << "    return 0;\n";
    } else if (indexed_lookup) {
        ds << fmt::format("    const uint32_t offset = want - 0x{:08X}u;\n", lookup_lo);
        ds << fmt::format("    if ((want & 3u) || offset > 0x{:X}u) return 0;\n", lookup_hi - lookup_lo);
        ds << "    const uint32_t index = k_psx_game_dispatch_index[offset >> 2];\n";
        ds << "    if (!index || k_psx_game_dispatch[index - 1u].addr != addr) return 0;\n";
        ds << "    return &k_psx_game_dispatch[index - 1u];\n";
    } else {
        ds << "    uint32_t lo = 0, hi = PSX_GAME_DISPATCH_COUNT;\n";
        ds << "    while (lo < hi) {\n";
        ds << "        uint32_t mid = lo + (hi - lo) / 2;\n";
        ds << "        uint32_t key = k_psx_game_dispatch[mid].addr & 0x1FFFFFFFu;\n";
        ds << "        if (want < key) hi = mid;\n";
        ds << "        else if (want > key) lo = mid + 1;\n";
        ds << "        else return k_psx_game_dispatch[mid].addr == addr ? &k_psx_game_dispatch[mid] : 0;\n";
        ds << "    }\n";
        ds << "    return 0;\n";
    }
    ds << "}\n\n";

    ds << "/* Exact static-code validity for this entry's emitted CFG ranges. */\n";
    ds << "int psx_game_text_native_ok(uint32_t addr) {\n";
    ds << "    const PsxGameDispatchEntry* entry = psx_game_find_entry(addr);\n";
    ds << "    if (!entry || entry->range_count == 0) return 0;\n";
    ds << "    return dirty_ram_text_native_ok_ranges_from(\n";
    ds << "        &k_psx_game_code_ranges[entry->range_index].lo, entry->range_count, addr);\n";
    ds << "}\n\n";

    ds << "/* Full-range validity for straight-line interpreter-to-AOT handoff. */\n";
    ds << "int psx_game_text_native_ok_full(uint32_t addr) {\n";
    ds << "    const PsxGameDispatchEntry* entry = psx_game_find_entry(addr);\n";
    ds << "    if (!entry || entry->range_count == 0) return 0;\n";
    ds << "    return dirty_ram_text_native_ok_ranges(\n";
    ds << "        &k_psx_game_code_ranges[entry->range_index].lo, entry->range_count);\n";
    ds << "}\n\n";

    ds << "/* Maps PS1 address to compiled game code. Returns 1 if dispatched, 0 if unknown. */\n";
    ds << "int psx_dispatch_game_compiled(CPUState* cpu, uint32_t addr) {\n";
    ds << "    const PsxGameDispatchEntry* entry = psx_game_find_entry(addr);\n";
    ds << "    if (!entry) return 0;\n";
    ds << "    if (entry->range_count == 0 || !dirty_ram_text_native_ok_ranges_from(\n";
    ds << "            &k_psx_game_code_ranges[entry->range_index].lo, entry->range_count, addr)) return 0;\n";
    ds << "    psx_check_interrupts_dispatch_entry(cpu, addr);\n";
    if (cps)
        ds << "    cpu->pc = entry->resume_pc;\n";
    ds << "    /* load_accel: cycle-faithful VSync(-1) query (config-gated). */\n";
    ds << "    {\n";
    ds << "        extern int psx_vsync_query_hle_try(CPUState* cpu, uint32_t addr);\n";
    ds << "        if (psx_vsync_query_hle_try(cpu, addr)) return 1;\n";
    ds << "    }\n";
    ds << "    entry->fn(cpu);\n";
    ds << "    return 1;\n";
    ds << "}\n";

    // Non-destructive companion to psx_dispatch_game_compiled: is `addr` a PC
    // the top-level dispatch can re-enter (a compiled function entry, or a CPS
    // continuation resume-point)? The precise event slicer (dirty_ram_interp.c)
    // needs this to know when it may hand a resume PC back to the dispatcher:
    // a MID-function clean-text PC is NOT re-enterable (the switch falls to
    // `default: return 0` and the dirty path returns 0 -> top-level PC=0 exit),
    // so the slicer must keep interpreting until cpu->pc lands on a true entry.
    // Same precise address set as dispatch, without executing the entry. The
    // runtime also asks it for the other segments' aliases of a missed PC to
    // tell a segment miss from an interior one.
    ds << "\n/* 1 iff addr is a re-enterable compiled entry/continuation (no exec). */\n";
    ds << "int psx_game_is_function_entry(uint32_t addr) {\n";
    ds << "    return psx_game_find_entry(addr) != 0;\n";
    ds << "}\n";

    if (cps) {
        // RECURSION_BUG.md §25 — mark CPS mode at startup so runtime code that
        // routes CPS continuations (overlay_loader.c) sees the contract.
        // Static ctor: no clash with the BIOS dispatch's marker.
        ds << "\n/* CPS runtime-mode marker (the overlay loader reads g_psx_cps_mode). */\n";
        ds << "static void psx_cps_mark_game(void) {\n";
        ds << "    extern int g_psx_cps_mode; g_psx_cps_mode = 1;\n";
        ds << "}\n";
        // Run psx_cps_mark_game before main(). __attribute__((constructor)) is
        // GCC/Clang-only; MSVC uses a static initializer pointer in .CRT$XCU.
        ds << "#if defined(_MSC_VER)\n";
        ds << "#pragma section(\".CRT$XCU\", read)\n";
        ds << "__declspec(allocate(\".CRT$XCU\")) static void (*psx_cps_mark_game_ctor)(void) = psx_cps_mark_game;\n";
        ds << "#else\n";
        ds << "__attribute__((constructor)) static void psx_cps_mark_game_ctor(void) { psx_cps_mark_game(); }\n";
        ds << "#endif\n";
    }

    out = ds.str();
    return true;
}

}  // namespace PSXRecomp
